# Site settings
title: Erdem Turançiftçi
email: erdem@erdemtu.com
description: >
  iOS developer blogging about iOS development,
  design and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erdemtu.com" # the base hostname & protocol for your site
twitter_username: netarum
github_username:  erdemtu

# Build settings
markdown: kramdown

# Enabled Gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
